// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0-VpI0jBqiTmEXOc5mGHzi7melXZFdhw',
    appId: '1:161952500120:web:9b83e3b433974a2dcb83ed',
    messagingSenderId: '161952500120',
    projectId: 'r-foods-1bc09',
    authDomain: 'r-foods-1bc09.firebaseapp.com',
    storageBucket: 'r-foods-1bc09.firebasestorage.app',
    measurementId: 'G-EL93E1E9EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbA6SdrPLHUPPqIu35tyy521AoV2UCmUU',
    appId: '1:161952500120:android:042f014104cda10acb83ed',
    messagingSenderId: '161952500120',
    projectId: 'r-foods-1bc09',
    storageBucket: 'r-foods-1bc09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBudrinfCi7Oy_ILQjk4x0qBFxWJ5vGU_0',
    appId: '1:161952500120:ios:a6877860073e3494cb83ed',
    messagingSenderId: '161952500120',
    projectId: 'r-foods-1bc09',
    storageBucket: 'r-foods-1bc09.firebasestorage.app',
    iosBundleId: 'com.example.rFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBudrinfCi7Oy_ILQjk4x0qBFxWJ5vGU_0',
    appId: '1:161952500120:ios:a6877860073e3494cb83ed',
    messagingSenderId: '161952500120',
    projectId: 'r-foods-1bc09',
    storageBucket: 'r-foods-1bc09.firebasestorage.app',
    iosBundleId: 'com.example.rFoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0-VpI0jBqiTmEXOc5mGHzi7melXZFdhw',
    appId: '1:161952500120:web:79d22f081df1b440cb83ed',
    messagingSenderId: '161952500120',
    projectId: 'r-foods-1bc09',
    authDomain: 'r-foods-1bc09.firebaseapp.com',
    storageBucket: 'r-foods-1bc09.firebasestorage.app',
    measurementId: 'G-DN43WVH68H',
  );
}
